version: '3.1'
services:
  clamav:
    image: easysoft/clamav:${BUILD_ID}
    container_name: clamav_server
    ports:
      - 3310:3310
    tty: true
    restart: unless-stopped
    tmpfs: /var/cache
    volumes:
      - clamd_data:/var/lib/clamav
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
volumes:
  clamd_data:
    driver: local
